import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/layout/Header";
// import Footer from "@/components/layout/Footer";
import CTA from "@/components/layout/CTA";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700'] });
// Import de la police Inter avec support des variables CSS


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased">
        <Header />
        <CTA />
        {children}
        <Footer />
      </body>
    </html>
  );
}
