// lib/projects.ts
export const listItems = [
  {
    slug: 'Installation-electrique',
    image: "/images/installation-electrique-neuve.webp",
    title: "Installation électrique complète",
    subtitle: "Appartements & villas à Aix En Provence",
    description: `Nous avons réalisé une installation électrique complète dans une villa neuve située dans les hauteurs de Aix En Provence. Le projet a inclus la pose de câblage général, l’installation d’un tableau électrique avec disjoncteurs différenciels, ainsi que l’intégration de prises, interrupteurs et éclairages dans toutes les pièces. L’objectif était de garantir un confort optimal, une sécurité maximale, et une conformité totale à la norme NF C 15-100. Nous avons également conseillé le client sur des solutions d’économie d’énergie adaptées à son logement.`,
    client: "Marc Dupuis",
    price: "1 590 €",
    category: "Installation électrique",
    date: "12 janvier 2024",
    location: "Quartier Puyricard, Aix-en-Provence",
  },
  {
    slug: 'Remise-aux-normes',
    image: "/images/norme-electrique.webp",
    title: "Remise aux normes NF C 15-100",
    subtitle: "Sécurité & conformité assurée",
    description: `Dans cet appartement ancien du centre-ville de Aix En Provence, notre équipe a procédé à une remise aux normes complète du réseau électrique. Le projet a nécessité le remplacement du tableau, le réagencement de plusieurs circuits défectueux, et l'ajout de protections différentielles. Nous avons travaillé en coordination avec le propriétaire pour planifier l'intervention sans perturber son quotidien. Cette opération a permis de garantir la sécurité des occupants et la conformité du bien aux exigences actuelles.`,
    client: "Claire Morel",
    price: "1 690 €",
    category: "Remise aux normes",
    date: "28 février 2024",
    location: "Centre-ville, Aix-en-Provence",
  },
  {
    slug: 'Remplacement-et-modernisation',
    image: "/images/Remplacement-et-modernisation.webp",
    title: "Rénovation tableau électrique",
    subtitle: "Remplacement et modernisation",
    description: `Le client nous a sollicités pour remplacer un ancien tableau électrique datant de plus de 25 ans. Nous avons installé un tableau moderne avec des modules modulaires facilement identifiables, des interrupteurs différentiels et des disjoncteurs de dernière génération. Grâce à cette modernisation, la sécurité du logement a été nettement améliorée, et le client bénéficie désormais d’un système plus fiable et évolutif en cas de travaux futurs.`,
    client: "Jean Lefèvre",
    price: "1 290 €",
    category: "Rénovation & modernisation",
    date: "9 mars 2024",
    location: "Les Milles, Aix-en-Provence",
  },
  {
    slug: 'Installation-LED',
    image: "/images/eclairage-exterieur-aix.webp",
    title: "Éclairage extérieur et jardin",
    subtitle: "Installation LED & économies d’énergie",
    description: `Nous avons été contactés pour concevoir un système d’éclairage extérieur autour d’une villa avec jardin et piscine. Après étude du terrain, nous avons installé des spots encastrés, des lampes murales LED basse consommation, et des détecteurs de mouvement. Le tout a été synchronisé avec une horloge crépusculaire pour un fonctionnement automatique. Le rendu final a permis à notre client d’améliorer la sécurité nocturne tout en mettant en valeur ses extérieurs.`,
    client: "Sophie Lambert",
    price: "890 €",
    category: "Éclairage extérieur",
    date: "15 avril 2024",
    location: "Quartier Luynes, Aix-en-Provence",
  },
  {
    slug: 'Panne-generale',
    image: "/images/Panne-générale.webp",
    title: "Dépannage en urgence à Aix En Provence",
    subtitle: "Panne générale ou disjoncteur HS",
    description: `Intervention réalisée en urgence un dimanche soir suite à une panne générale dans un appartement situé à Aix En Provence Ouest. Le client avait tout perdu : éclairage, électroménager et chauffage. Après diagnostic, nous avons identifié un disjoncteur principal défectueux, remplacé immédiatement. Le courant a été rétabli en moins de 2 heures. Nous avons également sécurisé le tableau avec des disjoncteurs neufs pour éviter toute récidive.`,
    client: "Nicolas Petit",
    price: "290 €",
    category: "Dépannage urgence",
    date: "6 mai 2024",
    location: "Pont de l’Arc, Aix-en-Provence",
  },
  {
    slug: 'Installation-de-prises-et-interrupteurs',
    image: "/images/Installation-de-prises-et-interrupteurs.webp",
    title: "Installation de prises et interrupteurs",
    subtitle: "Travaux rapides et soignés",
    description: `Dans un espace de coworking en rénovation à Aix En Provence, nous avons installé une vingtaine de prises électriques, interrupteurs modernes, et chargeurs muraux USB intégrés. L’objectif était de garantir une distribution optimale de l’électricité dans les bureaux tout en conservant une esthétique soignée. Les travaux ont été réalisés en une journée, sans perturber les autres corps de métier présents sur le chantier.`,
    client: "Émilie Garnier",
    price: "590 €",
    category: "Installation électrique",
    date: "23 juin 2024",
    location: "Quartier Jas-de-Bouffan, Aix-en-Provence",
  },
];
